services:
  server:
    build: .
    ports: 
      - "3000:3000"
      - "4983:4983"
    environment:
      NODE_ENV: dev
      SPOTIFY_REDIRECT_URI: "http://localhost:3000/api/callback/spotify"
    env_file: .env
