[build]
builder = "DOCKERFILE"
nixpacksPlan = {"providers":["bun"]}
dockerfilePath = "dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
