// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type SpotifyTokenPair struct {
	ID           int64          `json:"id"`
	AccessToken  string         `json:"access_token"`
	RefreshToken string         `json:"refresh_token"`
	Scope        sql.NullString `json:"scope"`
	CreatedAt    int64          `json:"created_at"`
	ExpiresAt    int64          `json:"expires_at"`
}
